steps:
  - label: ":bash: BATS unit tests"
    command: bats tests/
    plugins:
      - docker#v5.11.0:
          image: "bats/bats:latest"
          mount-checkout: true

  - label: ":junit: Test junit-process"
    command: "echo 'Test run complete'"
    plugins:
      - mergify/mergify-ci#${BUILDKITE_COMMIT}:
          action: junit-process
          report_path: "zfixtures/junit_example.xml"
          token: "${MERGIFY_CI_TOKEN}"
          mergify_api_url: "http://localhost:1080"

  - label: ":mag: Test scopes-git-refs"
    key: test-git-refs
    plugins:
      - mergify/mergify-ci#${BUILDKITE_COMMIT}:
          action: scopes-git-refs

  - label: ":upload: Test scopes-upload"
    depends_on: test-git-refs
    plugins:
      - mergify/mergify-ci#${BUILDKITE_COMMIT}:
          action: scopes-upload
          scopes: "backend,frontend"
          token: "${MERGIFY_CI_TOKEN}"
          mergify_api_url: "http://localhost:1080"

  - label: ":mag: Test scopes"
    plugins:
      - mergify/mergify-ci#${BUILDKITE_COMMIT}:
          action: scopes
          token: "${MERGIFY_CI_TOKEN}"
          mergify_api_url: "http://localhost:1080"
